### ISSUE TITLE
Compile PyTorch extension

### ISSUE THREAD

**Issue by a17brah** [EnzymeAD/Enzyme#1202]
Hi, 
I'm interested in using your library to generate the backward code for a PyTorch extension:  
https://gist.github.com/a17brah/4d0b4b3eafcdbe4bd5e6f2b5374649b8.

However, I'm currently encountering this error :
![image](https://github.com/EnzymeAD/Enzyme/assets/47603751/c4f8e848-e9ee-4d2b-a3c3-c36c828c94be)

**Comment by wsmoses** [comment]
Can you post the whole log?

**Comment by a17brah** [comment]
Here it is https://gist.github.com/a17brah/55ea82194f2b6f8bb4318aab024c323f  (for an other example). I couldn't get more than the printed log for the previous example.
Also, I played a bit with the library and I managed to get it to work by giving pointers to the data.

**Comment by wsmoses** [comment]
There are indeed. We have some folks working on the Fortran intel intrinsics currently. Are there particular intrinisics that you'd like?

You're using the torch add which takes arbitrary data (e.g. float, double, etc) all as a union which can make Enzyme unhappy. To enable union support try adding `-mllvm -enzyme-strict-aliasing=0`. You may also end up needing to use `-mllvm -enzyme-loose-types`.

However ironically it may be worthwhile just adding the torch add/etc as custom rules within Enzyme.

Alternatively, if you use Tensor<float> instead of the type generic Tensor this also may disappear.

cc @ZuseZ4
