### ISSUE TITLE
How to use lambdas and wrappers with reverse mode?

### ISSUE THREAD

**Issue by alecjacobson** [EnzymeAD/Enzyme#1686]
The examples for using `wrapper` show `__enzyme_fwddiff`. I'm trying but failing to adapt them to `__enzyme_autodiff`

https://fwd.gymni.ch/qzCwLm

(let me know if you prefer explorer links or to paste the code here).

**Comment by alecjacobson** [comment]
Here's another attempt. Using a less general wrapper, I can get it to compile but the derivatives are incorrect:

https://fwd.gymni.ch/mNzm5L

**Comment by alecjacobson** [comment]
OK, I think the incorrect derivatives are a more general C++ capturing-gotcha because I was trying to pass by value. Passing the lambda by reference gives the correctly derivatives for my less general `new_wrapper`

https://fwd.gymni.ch/IFoUkF

The variadic `wrapper` still not working though.

**Comment by alecjacobson** [comment]
One more, using pointer args seems to convince the compiler to allow using the variadic wrapper, b-b-b-b-but then Enzyme crashes:

https://fwd.gymni.ch/KjX4iz

**Comment by alecjacobson** [comment]
yet another, this time removing `&& args` → `args` for the wrapper makes everything compile and compute correct derivatives.

https://fwd.gymni.ch/nqEL3V

I'd still consider this unresolved because pass-by-value could mean a lot of copying.

**Comment by alecjacobson** [comment]
Thanks!

Probably I'm just confused by C++, but I'm surprised that `f` and `wrapper` don't need to have `double*` types (rather than `double`). I'm curious how the `__enzyme_autodiff` function knows to pass these as objects rather than the pointers that are provided in the dup parameters.

**Comment by wsmoses** [comment]
So essentially since we're in the compiler not the c++ syntactic sugar level (which again we should reduce the dissonance by making c++ syntactic sugar), `double&` is the same type as `double*`. Thus a function argument that expects a reference really should be passed a pointer.

For example, both of these would be valid.

```cpp
double2 __enzyme_autodiff(void*, int, void*, int, double*, double*, int, double*, double*);

...
    __enzyme_autodiff(
      (void*)(wrapper<decltype(f), double, double>), 
      enzyme_const, (void*)&f,
      enzyme_dup, &x, &mu.x, enzyme_dup, &y, &mu.y);
```

```cpp
double2 __enzyme_autodiff(void*, int, void*, int, double&, double&, int, double&, double&);

...
    __enzyme_autodiff(
      (void*)(wrapper<decltype(f), double, double>), 
      enzyme_const, (void*)&f,
      enzyme_dup, x, mu.x, enzyme_dup, y, mu.y);
```

Enzyme-autodiff doesn't do c++-level type checking so both of these are valid (which is the nice syntactic sugar we should add). However the reason why `double*` was easier as the solution I mentioned above is essentially because the declaration of autodiff above passed arguments by value, not reference (see below).
```
template < typename return_type, typename ... T >
return_type __enzyme_autodiff(void*, T ... );
```

This even if the original function took a reference, this declaration of autodiff would pass it by value (the same thing would happen for c var-args). This is worked around in my earlier code snippet by passing things as a pointer, which is the same datalayout as a c++ reference.
